# Site settings
name: Leila Turgarayeva
email: l.turgarayeva@gmail.com
url: url
description: "A blog and a portfolio"
author: "author"
title: "BlogFolio"
permalink: pretty
baseurl: /leilusen

# social
github:
  username: Leilusen

twitter:
  username: username
