# Site settings
name: Leila Turgarayeva
email: l.turgarayeva@gmail.com
url: url
description: "A blog and a portfolio"
author: "author"
title: "Blog of aspiring Data Scientist"
permalink: pretty
baseurl: 
excerpt_separator: <!--more-->

# social
github:
  username: Leilusen

twitter:
  username: username
